# https://taskfile.dev

version: '3'

# dotenv: ['.env']

tasks:
  default:
    cmds:
      - task --list-all
    silent: true

  update:
    desc: upgrade all the go modules
    cmds:
      - go get -u ./...
      
  pklgen:
    desc: autogenerate wire dependencies injection code
    cmds:
      - pkl-gen-go ./pkl/AppConfig.pkl --base-path saas
  
  wire:
    desc: autogenerate wire dependencies injection code
    dir: wireapp
    cmds:
      - wire

  entg:
    desc: regenerate ent code after we make any edits to `schema/*.go`
    cmds:
      - go run ./cmd/entg .

  migrate:
    desc: run db migration script for against ent scheam
    # deps: [entg]
    cmds:
      - go run ./cmd/dbmigrate .

  entnew:
    desc: create new ent schema `task entnew -- User`
    cmds:
      - go run -mod=mod entgo.io/ent/cmd/ent new --target "schema" {{.CLI_ARGS}}
  
  build:
    desc: create build files saas, api, cli 
    cmds:
      - go build -o ../tmp/saas
      - go build -o ../tmp/api ./cmd/api
      - go build -o ../tmp/cli ./cmd/cli