# https://taskfile.dev

version: '3'

# dotenv: ['.env']

includes:
  saas:
    taskfile: ./saas/Taskfile.yml
    dir: ./saas
  gql:
    taskfile: ./gql/Taskfile.yml
    dir: ./gql
  gqlsa:
    taskfile: ./gqlsa/Taskfile.yml
    dir: ./gqlsa
  configmgr:
    taskfile: ./configmgr/Taskfile.yml
    dir: ./configmgr