// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ChangePasswordInput struct {
	OldPassword     string `json:"oldPassword"`
	Password        string `json:"password"`
	PasswordConfirm string `json:"passwordConfirm"`
}

type OauthCallbackResponse struct {
	OatConnectionID string                 `json:"oatConnectionId"`
	Provider        string                 `json:"provider"`
	CacheID         string                 `json:"cacheId"`
	Metadata        map[string]interface{} `json:"metadata,omitempty"`
}

type OauthRequestInput struct {
	OatConnectionID string                 `json:"oatConnectionId"`
	RedirectURL     *string                `json:"redirectUrl,omitempty"`
	Metadata        map[string]interface{} `json:"metadata,omitempty"`
}

type ResetPasswordInput struct {
	Email           string `json:"email"`
	Token           string `json:"token"`
	Password        string `json:"password"`
	PasswordConfirm string `json:"passwordConfirm"`
}

type UpdateProfileInput struct {
	FirstName *string `json:"firstName,omitempty"`
	LastName  *string `json:"lastName,omitempty"`
	Company   *string `json:"company,omitempty"`
	Phone     *string `json:"phone,omitempty"`
}
