# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task --list-all
    silent: true

  update:
    desc: upgrade all the go modules
    cmds:
      - go get -u ./...
      
  pklgen:
    desc: generate pkl config 
    cmds:
      - pkl-gen-go ../config/pkl/MainConfig.pkl --base-path configmgr 
  